config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # check the sidekiq activity on http://localhost:3000/sidekiq
  mount Sidekiq::Web => 'sidekiq'

  mount Shrine.presign_endpoint(:cache) => "/s3/params"

  root 'store#index'
  resources :products do
    get :who_bought, on: :member
  end

  post 'carts', to: 'carts#create'
  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  # update line item qty
  post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"

  post 'line_items', to: "line_items#create"
  get 'line_items/:id', to: "line_items#show", as: "line_item"
  delete 'line_items/:id', to: "line_items#destroy"

  resources :orders
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :user, optional: true

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)

    if current_item
      current_item.quantity += 1
    else
      # save will be executed in line_items#create
      current_item = line_items.build(product_id: product.id, price: product.price)
    end

    current_item
  end

  def amount
    # leave calculate work to db instead of rails
    line_items.joins(:product).sum('products.price * line_items.quantity')
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: %i[show destroy]
  include RescueInvalidCart
  rescue_from ActiveRecord::RecordNotFound, with: :invaild_cart

  def show
    render layout: "authentication"
  end

  def destroy
    @cart.destroy
    redirect_to '/', notice: 'Your cart is currently deleted.' 
  end
end

app/views/carts/_cart.html.slim
article
  h2
    | Shopping Cart:

  table
    = render(cart.line_items)
    tfoot 
      tr 
        th[colspan="4"]
          | Total amount:
        td.price = number_to_currency(cart.amount, locale: :pl)

  .cart-actions
    = button_to "Empty cart", cart, method: :delete, remote: true, data: { confirm: 'Are you sure?' }
    - unless current_page?(controller: 'orders', action:'new')
      = button_to "Checkout", new_order_path, method: :get, class: "checkout"

app/views/carts/destroy.js.erb
cart = document.querySelector('.carts')
if ( cart !== null ) {
  cart.remove()
}

app/views/carts/show.html.slim
/ This is a shorthand that assuming @cart is a collection of Cart instances
= render @cart