config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # check the sidekiq activity on http://localhost:3000/sidekiq
  mount Sidekiq::Web => 'sidekiq'

  mount Shrine.presign_endpoint(:cache) => "/s3/params"

  root 'store#index'
  resources :products do
    get :who_bought, on: :member
  end

  post 'carts', to: 'carts#create'
  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  # update line item qty
  post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"

  post 'line_items', to: "line_items#create"
  get 'line_items/:id', to: "line_items#show", as: "line_item"
  delete 'line_items/:id', to: "line_items#destroy"

  resources :orders
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  # optional: true, the association will not have its presence validated
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true

  validates :product_id, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :cart_id, presence: true, unless: -> { :order_id }
  validates :order_id, presence: true, unless: -> { :cart_id }

  def subtotal
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  skip_before_action :authenticate_user!, only: [:create]
  before_action :only => [:create] do
    redirect_to new_user_session_path, notice: 'Please login before adding products to your cart.' unless current_user
  end
  before_action :set_cart, only: %i[create destroy]
  before_action :set_line_item, only: %i[update destroy]

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)
    
    respond_to do |format|
      if @line_item.save
        reset_counter
        format.html { redirect_to root_url }
        format.js { @current_item = @line_item }
      else
        format.html { render :new }
      end
    end
  end

  def add_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity += 1
    @line_item.save
    redirect_to '/'
  end
  
  def reduce_quantity
    @line_item = LineItem.find(params[:id])
    if @line_item.quantity > 1
      @line_item.quantity -= 1
    else
      @line_item.destroy
      session[:line_item_id] = nil
    end
    @line_item.save
    redirect_to '/'
  end

  def destroy
    @line_item.destroy
    session[:line_item_id] = nil

    redirect_to '/', notice: 'Product was successfully removed from your shopping cart.'
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def reset_counter
    session[:counter] = 0
  end

  def line_item_params
    params.require(:line_item).permit(:product_id, :cart_id, :quantity, :price)
  end
end

app/views/line_items/_line_item.html.slim
tr class="#{ line_item == @current_item ? 'line-item-highlight' : ''}"
  td = render_if_thumbnail(line_item.product)
  td = line_item.product.title
  td.quantity
    = line_item.quantity 
    |  x
  td.price
    = number_to_currency(line_item.subtotal, locale: :pl)
  td.update-item
    = link_to "Add (+1)", line_item_add_path(line_item), method: :post
    = link_to "Reduce (-1)", line_item_reduce_path(line_item), method: :post
    = link_to "Remove item", line_item_path(line_item), method: :delete

app/views/line_items/_line_item.text.slim
= sprintf("%2d x %s", line_item.quantity, truncate(line_item.product.title, length: 50))

app/views/line_items/create.js.erb
li = document.querySelector('.carts')
if (li == null) {
  li = document.createElement('div')
  li.classList.add('carts')
}

cart = document.querySelector('.side_nav')
li.innerHTML = "<%= j render(@cart) %>"
cart.appendChild(li)

session_counter = document.querySelector('header>p')
if (session_counter) {
  session_counter.remove()
}