config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # check the sidekiq activity on http://localhost:3000/sidekiq
  mount Sidekiq::Web => 'sidekiq'

  mount Shrine.presign_endpoint(:cache) => "/s3/params"

  root 'store#index'
  resources :products do
    get :who_bought, on: :member
  end

  post 'carts', to: 'carts#create'
  get 'carts/:id', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy'

  # update line item qty
  post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"

  post 'line_items', to: "line_items#create"
  get 'line_items/:id', to: "line_items#show", as: "line_item"
  delete 'line_items/:id', to: "line_items#destroy"

  resources :orders
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Świat Zabawek
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_pack_tag 'android-chrome-192x192.png', type: 'image/png'
  body
    header.main
      = link_to image_tag('logo.svg', alt: 'The Pragmatic Bookshelf'), '/'
      .account
        - if user_signed_in?
          p Hello, #{ current_user.name }
          .nav-links
            = link_to 'Edit profile', edit_user_registration_path
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          .nav-links.login
            = link_to "Sign up", new_user_registration_path
            = link_to "Login", new_user_session_path

    section.content
      nav.side_nav
        ul
          li
            span = time_now
          li
            = link_to 'Order List', orders_path
          - if current_user && current_user.admin
            li
              = link_to 'Product List', products_path
              a href="/#" 
          - if user_signed_in?
            .carts
              = render_if @cart && @cart.line_items.any?, @cart

      main class=controller.controller_name
        - if notice
          aside#notice = notice
        - if alert
          aside#alert = alert
        = yield

app/views/layouts/authentication.html.slim
doctype html
html
  head
    title Świat Zabawek
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_pack_tag 'android-chrome-192x192.png', type: 'image/png'
  body
    main.authentication
      header
        = link_to image_tag('logo.svg', alt: 'The Pragmatic Bookshelf'), '/'

      - if notice
        aside#notice
          = notice

      section = yield

app/views/layouts/backend.html.slim
doctype html
html
  head
    title Świat Zabawek Backend
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header.main
      = link_to image_tag('logo.svg', alt: 'The Pragmatic Bookshelf'), '/'
      h1
        = @page_title

    section.content
      nav.side_nav
        ul
          li
            span = time_now
          li

      main class=controller.controller_name
        = yield

app/views/layouts/no_cart.html.slim
doctype html
html
  head
    title Świat Zabawek Backend
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header.main
      = link_to image_tag('logo.svg', alt: 'The Pragmatic Bookshelf'), '/'
      h1
        = @page_title

    section.content
      nav.side_nav
        ul
          li
            span = time_now
          li

      main class=controller.controller_name
        = yield